= Data Formats

The Data for the app has 2 requirements, defined as follows

= Teams

The teams format is:
[source,yaml,indent=0]
----
me: FALLSIA
start_time: '19:30'
teams:
  CLONA:
    location: Musgrave Park, 7JB, Stockmans Ln, Belfast BT9, UK
    name: Clonard
----

`me` refers to which is "my team" from the list of teams included.
`start_time` is the default start time for matches in this league (optional)
each `team` entry then has the following values: +
`KEY`: is the keyname used to select this team in the matches list. Under each KEY are the full team details +
`name`: Full Name of the team +
`location`: Address in google maps for the team

= Matches

[source,yaml,indent=0]
----
duration: 3
matches:
- away: BROOM
  date: '2018-10-01'
  our_score: 2
  opp_score: 5
----

Fairly simple structure, home or away againt team, date and score. Team is a KEY to data within the Team data.

There are additional optional entries available: +
`label`: An optional label for the match description, e.g. "Devine Cup" +
`newdate`: If a match date is changed, then add the new date. Keeping the original date means that the ICS unique key remains the same and the match is moved within the calendar rather than duplicated.
